package RMT.Constants;

public class AppConstants {
    public static final String CONFIG_PROD_FILE_PATH= "./src/test/resources/config/config.prod.properties";
    public static final String CONFIG_UAT_FILE_PATH= "./src/test/resources/config/config.uat.properties";
    public static final String CONFIG_DEV_FILE_PATH= "./src/test/resources/config/config.dev.properties";
    public static final String CONFIG_STAGING_FILE_PATH= "./src/test/resources/config/config.prod.properties";
    public static final String LOGIN_PAGE_URL= "https://login.microsoftonline.com/84f6c4a1-90f3-4354-bc70-3c8cc829b998/oauth2/v2.0/authorize?client_id=e8984f6e-d5e0-4ba7-88eb-938a6bde4fe4&scope=User.Read%20openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Frms-uat.wcgt.in&client-request-";
    public static final String LOGIN_PAGE_TITLE="Sign in to your account";
    public static final String PROJECT_LISTINGS_PAGE_TITILE="Resource Management Tool";
    public static final String PROJECT_LISTING_PAGE_URL="https://rms-uat.wcgt.in/";
    public static final String SKILL_MASTER_PAGE_TITLE="OptiWise";
    public static final String REPORTS_PAGE_TITLE="Resource Management Tool";
    public static final String SKILL_MASTER_PAGE_URL="https://uat.optiwise.wcgt.in/skillmaster";
    public static final String REPORTS_PAGE_URL="https://uat.optiwise.wcgt.in/reports";
    public static final String REQUISITON_PAGE_URL="https://uat.optiwise.wcgt.in/create-requisition/085897/9-2-INTEL%2F9688-DET-%20R-2425-00003";
    public static final String SKILL_MASTER_DATA_SHEET_NAME="SkillMaster";
    public static final String Designation_MASTER_DATA_SHEET_NAME="Designation Master";
    public static final String SKILL_MASTER_SKILL_ADDITON_SUCCESS_MESSAGE="Skill Created.";
    public static final String REQUISITON_CREATED_MESSAGE="Requisition created successfully.";
    public static final String REQUSITON_DELETED_MESSAGE="Requisition deleted successfully";
    public static final String REQUSIITON_UPDATE_MESSAGE="Requisition updated successfully";
    public static final String SKILL_MASTER_SKILL_UPDATION_SUCCESS_MESSAGE="Skill Updated.";
    public static final String SKILL_ADDITION_SUCCESS_MESSAGE="Skill added successfully";
    public static final String DESIGNATION_MASTER_GRADE_PARTNER="GRD00001";
    public static final String DESIGNATION_MASTER_GRADE_Executive_Director="GRD00002";
    public static final String DESIGNATION_MASTER_GRADE_Director="GRD00003";
    public static final String DESIGNATION_MASTER_GRADE_Associate_Director="GRD00004";
    public static final String DESIGNATION_MASTER_GRADE_MANAGER="GRD00005";
    public static final String DESIGNATION_MASTER_GRADE_Assistant_MANAGER="GRD00006";
    public static final String DESIGNATION_MASTER_GRADE_ASSOCIATE="GRD00007";
    public static final String DESIGNATION_MASTER_GRADE_Graduate_Trainee="GRD00008";
    public static final String DESIGNATION_MASTER_GRADE_Trainee="GRD00009";
    public static final String TEST_DATA_SHEET_PATH="./src/test/TestData/SkillMater.xlsx";
    public static final String DESIGNATION_DATA_SHEET_PATH="./src/test/TestData/Designation Master.xlsx";
    public static final String CONFIG_USERNAME_KEY="username";
    public static final String CONFIG_PASSWORD_KEY="password";
    public static final String CONFIGURATION_PAGE_RUN_ENABLED_KEY="configuration.screen.run.enabled";
    public static final String CONFIGURATION_SCREEN_TITLE="Configurations";
    public static final String CONFIGURATION_ALLOWED_VALUE_DISABLED="-1";
    public static final String CONFIGURATION_ALLOWED_VALUE_ENABLED="1";
    public static final String CONFIGURATION_SAVE_SUCCESS_MESSAGE="Configuration saved successfully";
    public static final String CONFIGURATION_UPDATE_SUCCESS_MESSAGE="Configuration updated successfully";
    public static final String CONFIGURATION_UPDATE_VALIDATION_MESSAGE="Error updating configuration";
    public static final String CONFIGURATION_GENERIC_SUCCESS_FRAGMENT="success";
    public static final String CONFIGURATION_DUPLICATE_FRAGMENT="already exists";
    public static final String CONFIGURATION_CREATE_FAILED_MESSAGE="Failed to create configuration";
    public static final String CONFIGURATION_ALERT_CONDITION_ALLOCATION_COST_TITLE="Alert condition for Allocation Cost";
    public static final String CONFIGURATION_AMBER_CONDITION_BUDGET_CONSUMPTION_TITLE="Amber condition for Budget Consumption";
    public static final String CONFIGURATION_MATCH_RANGE_REQUISITION_TITLE="Match Range for System Suggestions for a Requisition";
    public static final String CONFIGURATION_ALERT_CONDITION_TIMESHEET_HOURS_TITLE="Alert condition for Timesheet Hours";
    public static final String CONFIGURATION_MAX_PARAMETERS_PREFERENCE_TITLE="Maximum number of parameters for selection in Preference screen";
    public static final String CONFIGURATION_REQUISITION_FORM_PARAMETERS_TITLE="Requisition Form Parameters";
    public static final String CONFIGURATION_APPENDED_CAPACITY_TITLE="Appended Capacity Configuration";
    public static final String CONFIGURATION_REASON_CONFIGURATIONS_TITLE="Reason Configurations";
    public static final String CONFIGURATION_CENTRAL_ALLOCATION_NEW_TITLE="Central Allocation Configuration. (New)";
    public static final String CONFIGURATION_ALERT_CONDITION_ALLOCATION_COST_VALUE_KEY="configuration.alert.allocation.cost.value";
    public static final String CONFIGURATION_AMBER_CONDITION_BUDGET_CONSUMPTION_VALUE_KEY="configuration.amber.budget.consumption.value";
    public static final String CONFIGURATION_MATCH_RANGE_REQUISITION_VALUE_KEY="configuration.match.range.requisition.value";
    public static final String CONFIGURATION_ALERT_CONDITION_TIMESHEET_HOURS_VALUE_KEY="configuration.alert.timesheet.hours.value";
    public static final String CONFIGURATION_MAX_PARAMETERS_PREFERENCE_VALUE_KEY="configuration.max.parameters.preference.value";
    public static final String CONFIGURATION_REQUISITION_FORM_PARAMETER_VALUE_KEY="configuration.requisition.form.parameter.value";
    public static final String CONFIGURATION_REASON_TYPE_VALUE_KEY="configuration.reason.type.value";
    public static final String CONFIGURATION_CONFLICT_REASON_VALUE_KEY="configuration.conflict.reason.value";
    public static final String CONFIGURATION_CENTRAL_ALLOCATION_BUSINESS_UNIT_KEY="configuration.central.allocation.business.unit";
    public static final String CONFIGURATION_CENTRAL_ALLOCATION_COMPETENCY_KEY="configuration.central.allocation.competency";
    public static final String CONFIGURATION_CENTRAL_ALLOCATION_COMPETENCY_CANDIDATES_KEY="configuration.central.allocation.competency.candidates";
    public static final String APPENDED_CONFIG_COMPETENCY_KEY="appended.config.competency";
    public static final String APPENDED_CONFIG_COMPETENCY_CANDIDATES_KEY="appended.config.competency.candidates";
    public static final String APPENDED_CONFIG_BU_SEARCH_TERM_KEY="appended.config.business.unit.search.term";
    public static final String APPENDED_CONFIG_HOURS_KEY="appended.config.hours";
    public static final String APPENDED_CONFIG_SUPERCOACH_BYPASS_KEY="appended.config.supercoach.bypass";
    public static final String APPENDED_CONFIG_COMPETENCY_DEFAULT="Due Diligence";
    public static final String APPENDED_CONFIG_COMPETENCY_CANDIDATES_DEFAULT="Due Diligence,Learning Solutions,People & Culture,ESG & Risk Consulting,Tax,Regulatory & Finance Consulting,Operations,Global Delivery,Transformation Consulting,Audit,GOA";
    public static final String APPENDED_CONFIG_BU_SEARCH_TERM_DEFAULT="Deals";
    public static final String APPENDED_CONFIG_HOURS_DEFAULT="2";
    public static final boolean APPENDED_CONFIG_SUPERCOACH_BYPASS_DEFAULT=false;
    public static final String CONFIGURATION_REASON_TYPE_VALUE="Conflict";
    public static final String CONFIGURATION_CONFLICT_REASON_VALUE="Urgent Resource Requirement";
    public static final String CONFIGURATION_CENTRAL_ALLOCATION_BUSINESS_UNIT_DEFAULT="Deals";
    public static final String CONFIGURATION_CENTRAL_ALLOCATION_COMPETENCY_DEFAULT="Learning Solutions";
    public static final String CONFIGURATION_CENTRAL_ALLOCATION_COMPETENCY_CANDIDATES_DEFAULT="Learning Solutions,ESG & Risk Consulting,Tax,Regulatory & Finance Consulting,Deals,Operations,Global Delivery,Transformation Consulting,Audit,GOA";
    public static final String CONFIGURATION_ALERT_CONDITION_ALLOCATION_COST_VALUE="75";
    public static final String CONFIGURATION_AMBER_CONDITION_BUDGET_CONSUMPTION_VALUE="85";
    public static final String CONFIGURATION_MATCH_RANGE_REQUISITION_VALUE="70";
    public static final String CONFIGURATION_ALERT_CONDITION_TIMESHEET_HOURS_VALUE="75";
    public static final String CONFIGURATION_MAX_PARAMETERS_PREFERENCE_VALUE="3";
    public static final String CONFIGURATION_REQUISITION_FORM_PARAMETER_VALUE="5";
    public static final int CONFIGURATION_PAGE_LOAD_WAIT_SECONDS=15;
    public static final int CONFIGURATION_OPTION_OPEN_WAIT_SECONDS=10;
    public static final int CONFIGURATION_DIALOG_WAIT_SECONDS=15;
    public static final int CONFIGURATION_DROPDOWN_WAIT_SECONDS=12;
    public static final int CONFIGURATION_FILTER_WAIT_SECONDS=10;
    public static final String ALLOCATION_UI_RUN_ENABLED_KEY="allocation.ui.run.enabled";
    public static final String ALLOCATION_JOB_CODE_KEY="allocation.job.code";
    public static final String ALLOCATION_SWITCH_CURRENT_ACCOUNT_ID_KEY="allocation.switch.current.account.id";
    public static final String ALLOCATION_SWITCH_USERNAME_KEY="allocation.switch.username";
    public static final String ALLOCATION_SWITCH_PASSWORD_KEY="allocation.switch.password";
    public static final String ALLOCATION_RESOURCE_NAME_KEY="allocation.resource.name";
    public static final String ALLOCATION_DESCRIPTION_KEY="allocation.description";
    public static final String ALLOCATION_SKILL_NAME_KEY="allocation.skill.name";
    public static final String ALLOCATION_REQUEST_HOURS_KEY="allocation.request.hours";
    public static final String ALLOCATION_SUBMIT_ENABLED_KEY="allocation.submit.enabled";
    public static final String ALLOCATION_CONFIRM_ON_SUBMIT_KEY="allocation.confirm.on.submit";
    public static final String ALLOCATION_EXPECTED_SUBMIT_MESSAGE_KEY="allocation.expected.submit.message";
    public static final String ALLOCATION_EXPECTED_UPDATE_MESSAGE_KEY="allocation.expected.update.message";
    public static final String ALLOCATION_INITIAL_BUSINESS_OFFSET_DAYS_KEY="allocation.initial.business.offset.days";
    public static final String ALLOCATION_UPDATE_START_BUSINESS_OFFSET_DAYS_KEY="allocation.update.start.business.offset.days";
    public static final String ALLOCATION_UPDATE_END_BUSINESS_OFFSET_DAYS_KEY="allocation.update.end.business.offset.days";
    public static final String ALLOCATION_JOB_CODE = "13-1-VISHR/3572-Ski-NR-2526-00001";
    public static final String ALLOCATION_REQUESTOR_ACCOUNT_ID = "RMSED.ResourceReq2";
    public static final String ALLOCATION_RESOURCE_ACCOUNT_ID = "RMSED.Resource5";
    public static final String ALLOCATION_RESOURCE_USERNAME = "";
    public static final String ALLOCATION_RESOURCE_PASSWORD = "";
    public static final String ALLOCATION_RESOURCE_NAME = "RMSED.Resource1";
    public static final String ALLOCATION_DESCRIPTION = "Automation allocation validation.";
    public static final String ALLOCATION_SKILL_NAME = "";
    public static final String ALLOCATION_REQUESTED_HOURS = "8";
    public static final boolean ALLOCATION_SUBMIT_ENABLED_DEFAULT = true;
    public static final boolean ALLOCATION_CONFIRM_ON_SUBMIT_DEFAULT = true;
    public static final String ALLOCATION_EXPECTED_SUBMIT_MESSAGE = "Allocation completed successfully";
    public static final String ALLOCATION_EXPECTED_UPDATE_MESSAGE = "Allocation updated successfully";
    public static final int ALLOCATION_INITIAL_BUSINESS_OFFSET_DAYS = 2;
    public static final int ALLOCATION_UPDATE_START_BUSINESS_OFFSET_DAYS = 3;
    public static final int ALLOCATION_UPDATE_END_BUSINESS_OFFSET_DAYS = 4;
    public static final int ALLOCATION_DATE_RETRY_ATTEMPTS = 8;
    public static final int ALLOCATION_GRID_STATUS_WAIT_SECONDS = 30;
    public static final int ALLOCATION_UPDATE_GRID_STATUS_WAIT_SECONDS = 20;
    public static final int ALLOCATION_EDITOR_CLOSE_WAIT_SECONDS = 12;
    public static final int ALLOCATION_TASK_ACCEPT_STATUS_WAIT_SECONDS = 15;
    public static final int ALLOCATION_TASK_VISIBILITY_WAIT_SECONDS = 90;
    public static final int ALLOCATION_TASK_VISIBILITY_POLL_SECONDS = 10;
    public static final String Search_JOB_BY_JOB_CODE=ALLOCATION_JOB_CODE;
    public static final String UPDATE_ALLOCATION_BY_JOB_CODE=ALLOCATION_JOB_CODE;
    public static final String CREATE_REQUISITION_FAILED="Requisition not created";
    public static final String UPDATE_REQUISITION_FAILED="Requisition Updation Failed";
    public static final String ADDTITION_OF_DELEGATE_FAILED="Addtion of Delegate Failed";
    public static final String UPDATION_OF_DELEGATE_FAILED="Updation  of Delegate Failed";
    public static final String ADDITION_OF_ADDTIONAL_EL_FAILED="Addtion of Additional EL  Failed";
    public static final String SYSTEM_SUGGESTED_CARD="Ritika Sharma \n" +
            "(Total-18)";
    public static final String UPDATED_SYSTEM_SUGGESTED_CARD="Ritika Sharma \n" +
            "(Total-21)";
    public static final String SYSTEM_SUGGESTION_CARD_NOT_VISIBLE="=====CARD NOT VISIBLE ======";
    public static final String DELETE_REQUISITON_BUTTON="====Delete Requisition Box Is Not Visible=====";
    public static final String EXPORT_BUTTON_ON_REQUISITON_PAGE="========Export btn is not working======";
    public static final String SEARCHED_SKILL_RESULT="Consultant";
    public static final String EMPLOYEE_SKILL_DESIGNATION="Associate Director";
    public static final String SKILL_SEARCH_BY_SKILL_NAME_NOT_FOUND="====SKILL NAME NOT FOUND======";
    public static final String SKILL_SEARCH_BY_EMPLOYEE_NAME_NOT_FOUND="====SKILL NOT FOUND TAGGED TO EMPLOYEE======";
    public static final String UPDATED_ALOCATION_STATUS="Allocation Complete";
    public static final String ADD_UPDATE_DELEGATE_SUCCESS_MESSAGE="Project details updated successfully!";
    public static final String ADDITION_UPDATION_OF_DELEGATE_IN_A_JOB="Project details updated successfully!";
    public static final String RESOURCE_RELEASED_SUCCESSFULLY="Resource released successfully";
    public static final String REPORTS_PAGE_CARD1_TITLE="Total Project";
    public static final String REPORTS_PAGE_CARD2_TITLE="Allocation";
    public static final String REPORTS_PAGE_CARD3_TITLE="Chargeable Allocation";
    public static final String REPORTS_PAGE_CARD4_TITLE="NC Allocation";
    public static final String REPORTS_PAGE_CARD5_TITLE="Allocation vs Capacity (hours)";
    public static final String REPORTS_PAGE_CARD6_TITLE="Allocation Hours";
    public static final String REPORTS_PAGE_CARD7_TITLE="Actuals vs Capacity (hours)";
    public static final String REPORTS_PAGE_CARD8_TITLE="Actual Hours";
    public static final String REPORTS_PAGE_CARD1_DATA="======CARD1 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_CARD2_DATA="======CARD2 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_CARD3_DATA="======CARD3 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_CARD4_DATA="======CARD4 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_CARD5_DATA="======CARD5 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_CARD6_DATA="======CARD6 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_CARD7_DATA="======CARD7 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_START_DATE="======START DATE NOT PRESENT=====";
    public static final String REPORTS_PAGE_END_DATE="======END DATE NOT PRESENT=====";
    public static final String CAPACITY_REPORTS_PAGE_CARD1_TITLE="Total Capacity";
    public static final String CAPACITY_REPORTS_PAGE_CARD2_TITLE="Total Allocation";
    public static final String CAPACITY_REPORTS_PAGE_CARD3_TITLE="Total Availability";
    public static final String CAPACITY_REPORTS_PAGE_CARD4_TITLE="Total Actual";
    public static final String CAPACITY_REPORTS_PAGE_CARD1_DATA="======CARD1 DATA NOT VISIBLE=====";
    public static final String CAPACITY_REPORTS_PAGE_CARD2_DATA="======CARD2 DATA NOT VISIBLE=====";
    public static final String CAPACITY_REPORTS_PAGE_CARD3_DATA="======CARD3 DATA NOT VISIBLE=====";
    public static final String CAPACITY_REPORTS_PAGE_CARD4_DATA="======CARD4 DATA NOT VISIBLE=====";
    public static final String EXPORT_BUTTON_ON_CAPACITY_REPORTS_PAGE="========Export btn is not working======";
    public static final String SCHEDULE_REPORTS_PAGE_DATA="======SCHEDULE VS VARIANCE CHART DATA  NOT PRESENT=====";
    public static final String EXPORT_BUTTON_ON_SCHEDULE_REPORTS_PAGE="========Export btn is not working======";
    public static final String RESOURCE_ALLOCATION_MESSAGE="Allocations submitted successfully";
    public static final String APPENDED_CAPACITY_CONFIG_SUCCESS_MESSAGE="Configuration saved successfully";
    public static final String ALLOCATION_PENDING_APPROVAL_MESSAGE="Pending Approval";
    public static final String ALLOCATION_APPROVED_MESSAGE="Allocation Complete";
    public static final String APPENDED_CAPACITY_INDICATOR_NOT_VISIBLE="Appended capacity indicator is not visible on Common Allocation screen.";
    public static final String BUDGET_PAGE_CARD1_TITLE="Job Fee";
    public static final String BUDGET_PAGE_CARD2_TITLE="No. of Resources";
    public static final String BUDGET_PAGE_CARD3_TITLE="Original Budget";
    public static final String BUDGET_PAGE_CARD4_TITLE="Revised Budget";
    public static final String BUDGET_PAGE_CARD5_TITLE="Allocations";
    public static final String BUDGET_PAGE_CARD6_TITLE="Actual";
    public static final String BUDGET_PAGE_CARD1_DATA="======CARD1 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CARD2_DATA="======CARD2 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CARD3_DATA="======CARD3 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CARD4_DATA="======CARD4 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CARD5_DATA="======CARD5 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CARD6_DATA="======CARD6 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CARD7_DATA="======CARD6 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART1_DATA="======CHART 1 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_GRID_GRADE_DATA="======GRID GRADE  DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_GRID_BUDGET_DATA="======GRID BUDGET  DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_GRID_ORIGNAL_BUDGET_DATA="======GRID ORIGINAL BUDGET   DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART3_DATA="======CHART 3 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART3_MONTHLY_DATA="======CHART 3 MONTHLY DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART3_QUARTERLY_DATA="======CHART 3 QUARTERLY DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_DATA="======CHART 4 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_LOCATION1_DATA="======LOCATION 1  DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_LOCATION2_DATA="======LOCATION 2  DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_GRADE_DATA="======GRADE  DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_DESIGNATION_DATA="======DESIGNATION DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_BU_DATA="======BUISNESS UNIT DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_COMPETENCY_DATA="======COMPETENCY  DATA NOT VISIBLE=====";
    public static final String SKILL_REVIEW_POP_UP_MESSAGE_FOR_SC = "Skill approved successfully";
    public static final String Skill_Status_Approved_From_SuperCoach="Approved";
}
