package RMT.Constants;

public class AppConstants {
    public static final String CONGIF_FILE_PATH= "./src/test/resources/config/config.properties";
    public static final String LOGIN_PAGE_URL= "https://login.microsoftonline.com/84f6c4a1-90f3-4354-bc70-3c8cc829b998/oauth2/v2.0/authorize?client_id=e8984f6e-d5e0-4ba7-88eb-938a6bde4fe4&scope=User.Read%20openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Frms-uat.wcgt.in&client-request-";
    public static final String LOGIN_PAGE_TITLE="Sign in to your account";
    public static final String PROJECT_LISTINGS_PAGE_TITILE="Resource Management Tool";
    public static final String PROJECT_LISTING_PAGE_URL="https://rms-uat.wcgt.in/";
    public static final String SKILL_MASTER_PAGE_TITLE="OptiWise";
    public static final String REPORTS_PAGE_TITLE="Resource Management Tool";
    public static final String SKILL_MASTER_PAGE_URL="https://uat.optiwise.wcgt.in/skillmaster";
    public static final String REPORTS_PAGE_URL="https://uat.optiwise.wcgt.in/reports";
    public static final String REQUISITON_PAGE_URL="https://uat.optiwise.wcgt.in/create-requisition/085897/9-2-INTEL%2F9688-DET-%20R-2425-00003";
    public static final String SKILL_MASTER_DATA_SHEET_NAME="SkillMaster";
    public static final String Designation_MASTER_DATA_SHEET_NAME="Designation Master";
    public static final String SKILL_MASTER_SKILL_ADDITON_SUCCESS_MESSAGE="Skill Created.";
    public static final String REQUISITON_CREATED_MESSAGE="Requisition created successfully.";
    public static final String REQUSITON_DELETED_MESSAGE="Requisition deleted successfully";
    public static final String REQUSIITON_UPDATE_MESSAGE="Requisition updated successfully";
    public static final String SKILL_MASTER_SKILL_UPDATION_SUCCESS_MESSAGE="Skill Updated.";
    public static final String SKILL_ADDITION_SUCCESS_MESSAGE="Skill added successfully";
    public static final String DESIGNATION_MASTER_GRADE_PARTNER="GRD00001";
    public static final String DESIGNATION_MASTER_GRADE_Executive_Director="GRD00002";
    public static final String DESIGNATION_MASTER_GRADE_Director="GRD00003";
    public static final String DESIGNATION_MASTER_GRADE_Associate_Director="GRD00004";
    public static final String DESIGNATION_MASTER_GRADE_MANAGER="GRD00005";
    public static final String DESIGNATION_MASTER_GRADE_Assistant_MANAGER="GRD00006";
    public static final String DESIGNATION_MASTER_GRADE_ASSOCIATE="GRD00007";
    public static final String DESIGNATION_MASTER_GRADE_Graduate_Trainee="GRD00008";
    public static final String DESIGNATION_MASTER_GRADE_Trainee="GRD00009";
    public static final String TEST_DATA_SHEET_PATH="./src/test/TestData/SkillMater.xlsx";
    public static final String DESIGNATION_DATA_SHEET_PATH="./src/test/TestData/Designation Master.xlsx";
    public static final String Search_JOB_BY_JOB_CODE="9-2-INTEL/9688-DET- R-2425-00003";
    public static final String UPDATE_ALLOCATION_BY_JOB_CODE="9-2-INTEL/9688-DET- R-2425-00003";
    public static final String CREATE_REQUISITION_FAILED="Requisition not created";
    public static final String UPDATE_REQUISITION_FAILED="Requisition Updation Failed";
    public static final String ADDTITION_OF_DELEGATE_FAILED="Addtion of Delegate Failed";
    public static final String UPDATION_OF_DELEGATE_FAILED="Updation  of Delegate Failed";
    public static final String ADDITION_OF_ADDTIONAL_EL_FAILED="Addtion of Additional EL  Failed";
    public static final String SYSTEM_SUGGESTED_CARD="Ritika Sharma \n" +
            "(Total-18)";
    public static final String UPDATED_SYSTEM_SUGGESTED_CARD="Ritika Sharma \n" +
            "(Total-21)";
    public static final String SYSTEM_SUGGESTION_CARD_NOT_VISIBLE="=====CARD NOT VISIBLE ======";
    public static final String DELETE_REQUISITON_BUTTON="====Delete Requisition Box Is Not Visible=====";
    public static final String EXPORT_BUTTON_ON_REQUISITON_PAGE="========Export btn is not working======";
    public static final String SEARCHED_SKILL_RESULT="Consultant";
    public static final String EMPLOYEE_SKILL_DESIGNATION="Associate Director ";
    public static final String SKILL_SEARCH_BY_SKILL_NAME_NOT_FOUND="====SKILL NAME NOT FOUND======";
    public static final String SKILL_SEARCH_BY_EMPLOYEE_NAME_NOT_FOUND="====SKILL NOT FOUND TAGGED TO EMPLOYEE======";
    public static final String UPDATED_ALOCATION_STATUS="Allocation Complete";
    public static final String ADD_UPDATE_DELEGATE_SUCCESS_MESSAGE="Project details updated successfully!";
    public static final String ADDITION_UPDATION_OF_DELEGATE_IN_A_JOB="Project details updated successfully!";
    public static final String RESOURCE_RELEASED_SUCCESSFULLY="Resource released successfully";
    public static final String REPORTS_PAGE_CARD1_TITLE="Total Project";
    public static final String REPORTS_PAGE_CARD2_TITLE="Allocation";
    public static final String REPORTS_PAGE_CARD3_TITLE="Chargeable Allocation";
    public static final String REPORTS_PAGE_CARD4_TITLE="NC Allocation";
    public static final String REPORTS_PAGE_CARD5_TITLE="Allocation vs Capacity (hours)";
    public static final String REPORTS_PAGE_CARD6_TITLE="Allocation Hours";
    public static final String REPORTS_PAGE_CARD7_TITLE="Actuals vs Capacity (hours)";
    public static final String REPORTS_PAGE_CARD8_TITLE="Actual Hours";
    public static final String REPORTS_PAGE_CARD1_DATA="======CARD1 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_CARD2_DATA="======CARD2 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_CARD3_DATA="======CARD3 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_CARD4_DATA="======CARD4 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_CARD5_DATA="======CARD5 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_CARD6_DATA="======CARD6 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_CARD7_DATA="======CARD7 DATA NOT VISIBLE=====";
    public static final String REPORTS_PAGE_START_DATE="======START DATE NOT PRESENT=====";
    public static final String REPORTS_PAGE_END_DATE="======END DATE NOT PRESENT=====";
    public static final String CAPACITY_REPORTS_PAGE_CARD1_TITLE="Total Capacity";
    public static final String CAPACITY_REPORTS_PAGE_CARD2_TITLE="Total Allocation";
    public static final String CAPACITY_REPORTS_PAGE_CARD3_TITLE="Total Availability";
    public static final String CAPACITY_REPORTS_PAGE_CARD4_TITLE="Total Actual";
    public static final String CAPACITY_REPORTS_PAGE_CARD1_DATA="======CARD1 DATA NOT VISIBLE=====";
    public static final String CAPACITY_REPORTS_PAGE_CARD2_DATA="======CARD2 DATA NOT VISIBLE=====";
    public static final String CAPACITY_REPORTS_PAGE_CARD3_DATA="======CARD3 DATA NOT VISIBLE=====";
    public static final String CAPACITY_REPORTS_PAGE_CARD4_DATA="======CARD4 DATA NOT VISIBLE=====";
    public static final String EXPORT_BUTTON_ON_CAPACITY_REPORTS_PAGE="========Export btn is not working======";
    public static final String SCHEDULE_REPORTS_PAGE_DATA="======SCHEDULE VS VARIANCE CHART DATA  NOT PRESENT=====";
    public static final String EXPORT_BUTTON_ON_SCHEDULE_REPORTS_PAGE="========Export btn is not working======";
    public static final String RESOURCE_ALLOCATION_MESSAGE="Allocations submitted successfully";
    public static final String BUDGET_PAGE_CARD1_TITLE="Job Fee";
    public static final String BUDGET_PAGE_CARD2_TITLE="No. of Resources";
    public static final String BUDGET_PAGE_CARD3_TITLE="Original Budget";
    public static final String BUDGET_PAGE_CARD4_TITLE="Revised Budget";
    public static final String BUDGET_PAGE_CARD5_TITLE="Allocations";
    public static final String BUDGET_PAGE_CARD6_TITLE="Actual";
    public static final String BUDGET_PAGE_CARD1_DATA="======CARD1 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CARD2_DATA="======CARD2 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CARD3_DATA="======CARD3 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CARD4_DATA="======CARD4 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CARD5_DATA="======CARD5 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CARD6_DATA="======CARD6 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CARD7_DATA="======CARD6 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART1_DATA="======CHART 1 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_GRID_GRADE_DATA="======GRID GRADE  DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_GRID_BUDGET_DATA="======GRID BUDGET  DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_GRID_ORIGNAL_BUDGET_DATA="======GRID ORIGINAL BUDGET   DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART3_DATA="======CHART 3 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART3_MONTHLY_DATA="======CHART 3 MONTHLY DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART3_QUARTERLY_DATA="======CHART 3 QUARTERLY DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_DATA="======CHART 4 DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_LOCATION1_DATA="======LOCATION 1  DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_LOCATION2_DATA="======LOCATION 2  DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_GRADE_DATA="======GRADE  DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_DESIGNATION_DATA="======DESIGNATION DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_BU_DATA="======BUISNESS UNIT DATA NOT VISIBLE=====";
    public static final String BUDGET_PAGE_CHART4_COMPETENCY_DATA="======COMPETENCY  DATA NOT VISIBLE=====";
}
